sudo: false
language: node_js
script:
  - curl https://raw.githubusercontent.com/shapesecurity/CLA/master/cla-travis.sh | bash
  - npm run build
  - npm test
node_js:
  - "0.12"
  - "4"
  - "5"
matrix:
  allow_failures:
    - node_js: "iojs-3"